#Faça um programa que leia algo e o disseque:
n = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(n))
print('É alfanumérico? ', n.isalnum())
print('É alfabético? ', n.isalpha())
print('É ASCII? ', n.isascii())
print('É dígito? ', n.isdigit())
print('Está em minúsculo? ', n.islower())
print('É decimal? ', n.isdecimal())
print('É identificador?', n.isidentifier())
print('É um número? ', n.isnumeric())
print('É imprimível? ', n.isprintable())
print('Só tem espaços? ', n.isspace())
print('Está capitalizado?', n.istitle())
print('Está em maiúsuculo? ', n.isupper())