#!/usr/bin/env bash

s=$1

case "$s" in
  dave) echo hi dave;;
  buddy) echo ohhh there he is;;
  guy) echo uh oh here comes trouble;;
  *) echo Idk who you are;;
esac


hello() {
  local s=$1
  echo "hello $s!"
}

goodbye() {
  local s=$1
  echo "goodbye $s!"
}

if (($# == 0)); then
  echo "name required!" >&2 
  exit 1
fi

for name in "$@"; do
  # you can use | as an "or" opearator in cases
  # unlike most places, you do a single | rather than ||
  case "$name" in
    d* | b*) hello "$name";;
    b*) hello "$name";;
    *) goodbye "$name";;
  esac
done
