#!/usr/bin/env bash

# read -p "Enter your name: " name
# echo "hello $name"

# you can also give arguments into variables
# rather than using user prompts

# name=$1
# echo "hello $name"

# this would print the first argument we gave
# so if we ran ./hello vitt
# it would return hello vitt

# conditionals
# -n here is looking for if $1 variable is set

if [[ -n $1 ]]; then
  name=$1
else
  read -p "Enter your name: " name
fi

echo "hello $name"
