#!/usr/bin/env bash

# this will read any output you give it after the command runs
# under the zettelkasten directory
# read zettelkasten
# echo "you said $zettelkasten"

# read has some weird behavior when using backslashes \
# because of that, it's better to use read -r
read -r zettelkasten
echo "you said $zettelkasten"

# which basically reads the string raw
# read only reads the first line

while read -r line; do
  # in bash, this field HAS to be filled
  # or it will be considered invalid syntax
  echo "we read line $line"
done
